# Generated by Django 5.2.8 on 2026-01-02 19:04

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': (('users.see_private', "Users can see other user's profiles"), ('users.edit_others', "Users can edit other user's profiles"))},
        ),
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='users/default_avatar.png', null=True, upload_to=users.models.Profile.user_directory_path),
        ),
    ]
