# Generated by Django 5.2.8 on 2026-01-07 20:28

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_follow_profile_followers'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar_is_set',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(null=True, upload_to=users.models.Profile.user_directory_path),
        ),
    ]
