# Generated by Django 5.2.8 on 2025-11-25 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('started_at', models.DateTimeField()),
                ('last_edited', models.DateTimeField()),
                ('published_at', models.DateTimeField()),
                ('is_published', models.BooleanField()),
            ],
        ),
    ]
