"""Django settings for main project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

def bool_env(env, default='false'):
    TRUE_VALUES = ('1', 'true')
    
    var = os.environ.get(env, default).lower()
    return var in TRUE_VALUES

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

ROOT_URLCONF = 'main.urls'
WSGI_APPLICATION = 'main.wsgi.application'

# region security
SECRET_KEY = os.environ.get('SECRET_KEY')
DEBUG = bool_env('DEBUG')

ALLOWED_HOSTS = []
if not DEBUG:
    ALLOWED_HOSTS = [
        'www.serkosal.org',
        'serkosal.org',
        'mail.serkosal.org',
        '63.250.47.103',
    ]

    CSRF_TRUSTED_ORIGINS = [
        'https://serkosal.org',
        'https://www.serkosal.org',
    ]

if bool_env('LOCALHOST_ALLOWED'): 
    ALLOWED_HOSTS.extend(['127.0.0.1', 'localhost'])

# endregion

# region apps and middlewares

INSTALLED_APPS = [
    # 3rd-party apps
    'modeltranslation',
    'taggit',
    'django_vite',
    "allauth",
    "allauth.account",
    # my own apps
    'users',
    'main',
    'blog',
    # django built in
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sitemaps',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    "allauth.account.middleware.AccountMiddleware", #allauth
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.locale.LocaleMiddleware'
]

# endregion

# region AUTH

AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
    "allauth.account.auth_backends.AuthenticationBackend",
]

ACCOUNT_SIGNUP_FIELDS = ['username*', 'email*', 'password1*', 'password2*']
ACCOUNT_LOGIN_METHODS = {'username', 'email'}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
     'NAME': 
     'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
     'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
     'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
     'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

LOGOUT_REDIRECT_URL = '/blog/'
LOGIN_REDIRECT_URL = "/"

# endregion

# region email
if not DEBUG and not bool_env('USE_MOCK_EMAIL'):
    EMAIL_HOST = os.environ.get('EMAIL_HOST')
    EMAIL_PORT = os.environ.get('EMAIL_PORT') or 587
    EMAIL_USE_TLS = bool_env('EMAIL_USE_TLS')
    EMAIL_TIMEOUT = 30
    
    EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER') or 'user@example.com'
    EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD') or ''
    
    DEFAULT_FROM_EMAIL = 'admin' + EMAIL_HOST_USER[EMAIL_HOST_USER.find('@'):]

else:
    EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"

ACCOUNT_EMAIL_VERIFICATION = "optional"
    
# endregion


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / 'templates',    
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.media',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


# region logging
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
        
        # to disable DisallowedHost
        'file_disallowed': {
            'class': 'logging.NullHandler',
        },

        
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        # disabling DisallowedHost error
        'django.security.DisallowedHost': {
            'handlers': ['file_disallowed'],
            'propagate': False,
            'level': 'ERROR',
        },
        'django': {
            'handlers': ['console'],
            'level': 'ERROR',
            'propagate': True,
        },
    },
}

# endregion

# region Databases
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

USE_SQLITE = bool_env('USE_SQLITE')
if USE_SQLITE:
    db_name = ('db.sqlite3' if DEBUG  else 'dev_db.sqlite3')
    
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / f'../db/sqlite/{db_name}',
            'TEST': {
                'NAME': 'testdb',
                'ENGINE': 'django.db.backends.sqlite3'
            }
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv('POSTGRES_DB'),
            'USER': os.getenv('POSTGRES_USER'),
            'PASSWORD': os.getenv('POSTGRES_PASSWORD'),
            'HOST': os.getenv('POSTGRES_HOST'),
            'PORT': os.getenv('POSTGRES_PORT'),
            'TEST': {
                'NAME': 'testdb',
                'ENGINE': 'django.db.backends.sqlite3'
            }
        }
    }
    
# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# endregion

# region Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'
LANGUAGES = [
    ('en', 'English'),
    ('ru', 'Russian')
]
LOCALE_PATHS = [
    BASE_DIR / "main/locale",
]

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# endregion

# region CELERY
CELERY_BROKER_URL = 'amqp://guest:guest@rabbitmq:5672//'
CELERY_RESULT_BACKEND = 'rpc://'

CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'UTC'

# endregion 

# region static files
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_ROOT = BASE_DIR / '../staticfiles'

STATICFILES_DIRS = [
    BASE_DIR / '../static',
    #'/app/backend/static', # when running inside docker
]

MEDIA_ROOT = BASE_DIR / '../media'

MEDIA_URL = '/media/'
STATIC_URL = 'static/'


# django vite
FRONTEND_HMR = bool_env('FRONTEND_HMR')
DJANGO_VITE = {
    "default": {
        "dev_mode": FRONTEND_HMR,
        "dev_server_host": "localhost",
        "dev_server_port": 5173,
        "dev_server_protocol": "http",
    }
}

# endregion
