# Generated by Django 5.2.8 on 2025-12-06 10:38

import blog.models
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_content_alter_post_is_published_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='post',
            managers=[
                ('posts', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.JSONField(default=blog.models.Post.content_default),
        ),
    ]
