# Generated by Django 5.2.8 on 2026-04-11 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0007_alter_post_content"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="is_published",
        ),
    ]
