# Generated by Django 5.2.8 on 2026-04-11 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0008_remove_post_is_published"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="views_num",
            field=models.BigIntegerField(default=0),
        ),
    ]
