# Generated by Django 5.2.8 on 2026-04-19 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0010_alter_post_published_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="content_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="content_ru",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="title_en",
            field=models.CharField(
                blank=True, default="Title", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="title_ru",
            field=models.CharField(
                blank=True, default="Title", max_length=100, null=True
            ),
        ),
    ]
