# Generated by Django 5.2.8 on 2026-04-27 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0011_post_content_en_post_content_ru_post_title_en_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="slug",
            field=models.SlugField(blank=True, max_length=120, null=True, unique=True),
        ),
    ]
